# Generated by Django 3.1.7 on 2021-07-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('content', models.TextField(blank=True, null=True)),
                ('is_complete', models.IntegerField()),
            ],
            options={
                'db_table': 'daily_todo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserSchedule',
        ),
    ]
